# Generated by Django 4.2.4 on 2023-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_book_last_update_book_rec1_book_rec2_book_rec3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
