# Generated by Django 4.2.4 on 2023-08-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_remove_book_id_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='recommender.writer'),
        ),
    ]
